### ISSUE TITLE
Segregar las interfaces de modalidad, tipo de pregunta, etc.

### ISSUE THREAD

**Issue by Jonathan-R0** [thiagokovnat/Kahoot-TP2#12]
Parcial y Penalidad tienen métodos definidos que no usan (puntuar los OrderedChoice y GroupChoice), viola la cuarta regla de los principios SOLID.

**Comment by matias-av** [comment]
Ahí segregue la interfaz Modalidad. No sé si el método admiteMultiplicador() se podría segregar también, en principio creo que hacerlo estaría de más.

**Comment by matias-av** [comment]
> Ahí segregue la interfaz Modalidad. No sé si el método admiteMultiplicador() se podría segregar también, en principio creo que hacerlo estaría de más.

Retiro lo dicho, en mi opinión no se debería segregar ya que obligatoriamente cada interfaz Modalidad tiene que tener si o si ese método.
Además, probé hacer que cada interfaz Modalidad herede de alguna otra interfaz que tenga la firma admiteMultiplicador() (Para no repetir código), pero al parecer Java no admite las interfaces que implementen otras interfaces.
