### ISSUE TITLE
Elevar excepcion en los metodos de modalidad que no deberian ser accedidos

### ISSUE THREAD

**Issue by thiagokovnat** [thiagokovnat/Kahoot-TP2#17]

**Comment by matias-av** [comment]
Fijate que en el commit 1586ca71367c6f344890755ee401341ee359dc85 segregué la interfaz de Modalidad, de tal forma que nunca deberían accederse a métodos de puntar que no correspondan al tipo. Así que creo que ya no hace falta hacer esto.
